--Teilaufgabe 1.c)

SELECT DISTINCT C.NAME 
FROM CD C, AUFNAHME A, AUFNAHME A2, STUECK S, STUECK S2
WHERE C.CDNR = A.CDNR  AND C.CDNR = A2.CDNR
AND A.SNR= S.SNR AND A2.SNR = S2.SNR 
AND (S.KNR <> S2.KNR) AND (S.SNR <> S2.SNR) 