--Teilaufgabe 1.a)

SELECT K.NAME, C.NAME, C.GESAMTSPIELZEIT AS min, S.SNR
FROM KOMPONIST K, STUECK S, CD C, AUFNAHME A
WHERE K.KNR = S.KNR
AND C.CDNR = A.CDNR
AND S.SNR = A.SNR 
AND (K.NAME = 'Telemann' OR K.NAME = 'Vivaldi')