--Teilaufgabe 1.b)

SELECT K.NAME, K.VORNAME, K.GEBOREN, K.GESTORBEN, (K2.GEBOREN-K.GEBOREN) AS ALTER 
FROM KOMPONIST K, KOMPONIST K2 
WHERE 
K2.NAME = 'Mozart' AND K2.VORNAME = 'Wolfgang Amadeus'
AND K.GESTORBEN >= K2.GEBOREN 
AND K.GEBOREN <= K2.GESTORBEN
AND K.NAME != K2.NAME AND K.VORNAME != K2.VORNAME